{
"name": "Deploy Dev",
"on": { "workflow_dispatch": {}, "push": { "branches": ["develop"] } },
"jobs": {
"deploy": {
"runs-on": "ubuntu-latest",
"environment": "sviluppo",
"steps": [
{ "name": "Checkout", "uses": "actions/checkout@v4" },
{
"name": "Setup SSH",
"run": "mkdir -p ~/.ssh && printf '%s' "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 && ssh-keyscan -H "${{ secrets.DEV_SSH_HOST }}" >> ~/.ssh/known_hosts"
},
{
"name": "Test SSH",
"run": "ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 "${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }}" 'echo ok && whoami && hostname'"
}
]
}
}
}
