{
"name": "Deploy Prod",
"on": { "workflow_dispatch": {}, "push": { "branches": ["main"] } },
"jobs": {
"deploy": {
"runs-on": "ubuntu-latest",
"environment": "stabile",
"steps": [
{ "name": "Checkout", "uses": "actions/checkout@v4" },
{
"name": "Setup SSH",
"run": "mkdir -p ~/.ssh && chmod 700 ~/.ssh && printf '%s' \"${{ secrets.PROD_SSH_KEY_B64 }}\" | base64 -d > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 && ssh-keyscan -H \"${{ secrets.PROD_SSH_HOST }}\" >> ~/.ssh/known_hosts"
},
{
"name": "Test SSH",
"run": "ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 \"${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}\" 'echo ok && whoami && hostname'"
},
{
  "name": "Rsync to PROD (real, with backup)",
  "env": {
    "HOST": "${{ secrets.PROD_SSH_HOST }}",
    "USER": "${{ secrets.PROD_SSH_USER }}",
    "DEST": "${{ secrets.PROD_PATH }}"
  },
  "run": "rsync -az -vv --itemize-changes --stats --delete --exclude='.git/' --exclude='.github/' --exclude='node_modules/' --filter='protect .env' --filter='protect *.sql' --filter='protect *.zip' --filter='protect *.tar' --filter='protect *.gz' --filter='protect backup_*' --filter='protect dump_*' --filter='protect export_*' --filter='protect mysql' --filter='protect mysql/' --filter='protect snap' --filter='protect snap/' --filter='protect **/.DS_Store' --backup --backup-dir=\"$DEST/.rsync-backup-${GITHUB_RUN_ID}\" -e \"ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes\" ./ \"$USER@$HOST:$DEST/\""
}
{
"name": "Post-deploy (pm2 reload/start)",
"env": { "HOST": "${{ secrets.PROD_SSH_HOST }}", "USER": "${{ secrets.PROD_SSH_USER }}", "DEST": "${{ secrets.PROD_PATH }}", "APP_NAME": "produ-prod", "NODE_ENV": "production" },
"run": "ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 \"$USER@$HOST\" \"bash -lc 'cd \\\"$DEST\\\" && chmod +x scripts/post_deploy_prod.sh && APP_NAME=\\\"$APP_NAME\\\" NODE_ENV=\\\"$NODE_ENV\\\" ./scripts/post_deploy_prod.sh'\""
}
]
}

}
}

