{
"name": "Deploy Prod",
"on": { "workflow_dispatch": {}, "push": { "branches": ["main"] } },
"jobs": {
"deploy": {
"runs-on": "ubuntu-latest",
"environment": "stabile",
"steps": [
{ "name": "Checkout", "uses": "actions/checkout@v4" },
{
"name": "Setup SSH",
"run": "mkdir -p ~/.ssh && chmod 700 ~/.ssh && printf '%s' \"${{ secrets.PROD_SSH_KEY_B64 }}\" | base64 -d > ~/.ssh/id_ed25519 && chmod 600 ~/.ssh/id_ed25519 && ssh-keyscan -H \"${{ secrets.PROD_SSH_HOST }}\" >> ~/.ssh/known_hosts"
},
{
"name": "Test SSH",
"run": "ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 \"${{ secrets.PROD_SSH_USER }}@${{ secrets.PROD_SSH_HOST }}\" 'echo ok && whoami && hostname'"
},
{
"name": "Rsync to PROD (dry-run)",
"env": {
"HOST": "${{ secrets.PROD_SSH_HOST }}",
"USER": "${{ secrets.PROD_SSH_USER }}",
"DEST": "${{ secrets.PROD_PATH }}"
},
"run": "rsync -azn -vv --itemize-changes --stats --delete --exclude='.git/' --exclude='.github/' --exclude='node_modules/' -e \"ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes\" ./ \"$USER@$HOST:$DEST/\""
}
]
}
}
}
