name: Test SSH Dev
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    environment:
      name: sviluppo
    steps:
      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh
          printf '%s' "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.DEV_SSH_HOST }}" >> ~/.ssh/known_hosts
      - name: Connect and print info
        shell: bash
        env:
          DEV_SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          DEV_SSH_USER: ${{ secrets.DEV_SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 "${DEV_SSH_USER}@${DEV_SSH_HOST}" 'whoami && hostname && pwd && ls -la "$HOME"'
