name: Test SSH Dev
on:
workflow_dispatch:
jobs:
test:
runs-on: ubuntu-latest
environment: sviluppo
steps:
- name: Setup SSH
run: |
mkdir -p ~/.ssh
echo "${{ secrets.DEV_SSH_KEY }}" > ~/.ssh/id_ed25519
chmod 600 ~/.ssh/id_ed25519
ssh-keyscan -H "${{ secrets.DEV_SSH_HOST }}" >> ~/.ssh/known_hosts
- name: Connect and print info
run: |
ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_ed25519 ${{ secrets.DEV_SSH_USER }}@${{ secrets.DEV_SSH_HOST }} 'whoami && hostname && pwd && ls -la $HOME'
